---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-spring
  template:
    metadata:
      labels:
        app: hello-world-spring
    spec:
      containers:
        - name: hello-world-spring
          image: gespenzt/cicd-jenkins:latest
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-spring
  labels:
    app: hello-world-spring
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8888
  selector:
    app: hello-world-spring
  type: LoadBalancer