apiVersion: v1
kind: Namespace
metadata:
  name: cicd-jenkins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: cicd-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: gespenzt/cicd-jenkins:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
  labels:
    app: go-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8888
  selector:
    app: go-service
  type: LoadBalancer