apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-spring
  namespace: cicd-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-spring
  template:
    metadata:
      labels:
        app: hello-world-spring
    spec:
      containers:
      - name: hello-world-spring
        image: gespenzt/cicd-jenkins:latest
        ports:
        - containerPort: 8888