apiVersion: v1
kind: Service
metadata:
  name: java-app
  labels:
    app: java-app
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8888
  selector:
    app: java-app
  type: LoadBalancer
  