apiVersion: v1
kind: Service
metadata:
  name: hello-world-spring
  labels:
    app: hello-world-spring
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8888
  selector:
    app: hello-world-spring
  type: LoadBalancer
  